# This is a basic workflow to help you get started with Actions

name: Run Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CACHE_VERSION: 1
  DEFAULT_PYTHON: 3.13
  PRE_COMMIT_CACHE: ~/.cache/pre-commit

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
permissions:
  contents: read

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
          cache: "pip"
          cache-dependency-path: requirements-dev.txt
      - name: Install dev dependencies
        run: pip install -r requirements-dev.txt
      - name: Restore pre-commit environment from cache
        id: cache-precommit
        uses: actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
        with:
          path: ${{ env.PRE_COMMIT_CACHE }}
          key: >-
            ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Install pre-commit dependencies
        if: steps.cache-precommit.outputs.cache-hit != 'true'
        run: pre-commit install-hooks
      - name: Run pre-commit
        run: pre-commit run --hook-stage manual --all-files --show-diff-on-failure
      - name: Run unit-tests
        run: python -m pytest --cov --cov-config=tox.ini --cov-report=term --cov-report=html
      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: test-coverage
          path: htmlcov
